// Generated by gencpp from file target_detector/MarkerPixel.msg
// DO NOT EDIT!


#ifndef TARGET_DETECTOR_MESSAGE_MARKERPIXEL_H
#define TARGET_DETECTOR_MESSAGE_MARKERPIXEL_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace target_detector
{
template <class ContainerAllocator>
struct MarkerPixel_
{
  typedef MarkerPixel_<ContainerAllocator> Type;

  MarkerPixel_()
    : id(0)
    , u(0.0)
    , v(0.0)  {
    }
  MarkerPixel_(const ContainerAllocator& _alloc)
    : id(0)
    , u(0.0)
    , v(0.0)  {
  (void)_alloc;
    }



   typedef uint32_t _id_type;
  _id_type id;

   typedef float _u_type;
  _u_type u;

   typedef float _v_type;
  _v_type v;





  typedef boost::shared_ptr< ::target_detector::MarkerPixel_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::target_detector::MarkerPixel_<ContainerAllocator> const> ConstPtr;

}; // struct MarkerPixel_

typedef ::target_detector::MarkerPixel_<std::allocator<void> > MarkerPixel;

typedef boost::shared_ptr< ::target_detector::MarkerPixel > MarkerPixelPtr;
typedef boost::shared_ptr< ::target_detector::MarkerPixel const> MarkerPixelConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::target_detector::MarkerPixel_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::target_detector::MarkerPixel_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::target_detector::MarkerPixel_<ContainerAllocator1> & lhs, const ::target_detector::MarkerPixel_<ContainerAllocator2> & rhs)
{
  return lhs.id == rhs.id &&
    lhs.u == rhs.u &&
    lhs.v == rhs.v;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::target_detector::MarkerPixel_<ContainerAllocator1> & lhs, const ::target_detector::MarkerPixel_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace target_detector

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::target_detector::MarkerPixel_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::target_detector::MarkerPixel_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::target_detector::MarkerPixel_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::target_detector::MarkerPixel_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::target_detector::MarkerPixel_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::target_detector::MarkerPixel_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::target_detector::MarkerPixel_<ContainerAllocator> >
{
  static const char* value()
  {
    return "c6d7f7e63e402c2bfb95b9659cdc90fc";
  }

  static const char* value(const ::target_detector::MarkerPixel_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xc6d7f7e63e402c2bULL;
  static const uint64_t static_value2 = 0xfb95b9659cdc90fcULL;
};

template<class ContainerAllocator>
struct DataType< ::target_detector::MarkerPixel_<ContainerAllocator> >
{
  static const char* value()
  {
    return "target_detector/MarkerPixel";
  }

  static const char* value(const ::target_detector::MarkerPixel_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::target_detector::MarkerPixel_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# AR 码像素坐标\n"
"uint32 id          # 标签 ID\n"
"float32 u          # 像素列坐标 (x)\n"
"float32 v          # 像素行坐标 (y)\n"
;
  }

  static const char* value(const ::target_detector::MarkerPixel_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::target_detector::MarkerPixel_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.id);
      stream.next(m.u);
      stream.next(m.v);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct MarkerPixel_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::target_detector::MarkerPixel_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::target_detector::MarkerPixel_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "id: ";
    Printer<uint32_t>::stream(s, indent + "  ", v.id);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "u: ";
    Printer<float>::stream(s, indent + "  ", v.u);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "v: ";
    Printer<float>::stream(s, indent + "  ", v.v);
  }
};

} // namespace message_operations
} // namespace ros

#endif // TARGET_DETECTOR_MESSAGE_MARKERPIXEL_H
