// Generated by gencpp from file target_detector/MarkerPixelArray.msg
// DO NOT EDIT!


#ifndef TARGET_DETECTOR_MESSAGE_MARKERPIXELARRAY_H
#define TARGET_DETECTOR_MESSAGE_MARKERPIXELARRAY_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>
#include <target_detector/MarkerPixel.h>

namespace target_detector
{
template <class ContainerAllocator>
struct MarkerPixelArray_
{
  typedef MarkerPixelArray_<ContainerAllocator> Type;

  MarkerPixelArray_()
    : header()
    , markers()  {
    }
  MarkerPixelArray_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , markers(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef std::vector< ::target_detector::MarkerPixel_<ContainerAllocator> , typename std::allocator_traits<ContainerAllocator>::template rebind_alloc< ::target_detector::MarkerPixel_<ContainerAllocator> >> _markers_type;
  _markers_type markers;





  typedef boost::shared_ptr< ::target_detector::MarkerPixelArray_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::target_detector::MarkerPixelArray_<ContainerAllocator> const> ConstPtr;

}; // struct MarkerPixelArray_

typedef ::target_detector::MarkerPixelArray_<std::allocator<void> > MarkerPixelArray;

typedef boost::shared_ptr< ::target_detector::MarkerPixelArray > MarkerPixelArrayPtr;
typedef boost::shared_ptr< ::target_detector::MarkerPixelArray const> MarkerPixelArrayConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::target_detector::MarkerPixelArray_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::target_detector::MarkerPixelArray_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::target_detector::MarkerPixelArray_<ContainerAllocator1> & lhs, const ::target_detector::MarkerPixelArray_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.markers == rhs.markers;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::target_detector::MarkerPixelArray_<ContainerAllocator1> & lhs, const ::target_detector::MarkerPixelArray_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace target_detector

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::target_detector::MarkerPixelArray_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::target_detector::MarkerPixelArray_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::target_detector::MarkerPixelArray_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::target_detector::MarkerPixelArray_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::target_detector::MarkerPixelArray_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::target_detector::MarkerPixelArray_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::target_detector::MarkerPixelArray_<ContainerAllocator> >
{
  static const char* value()
  {
    return "44de9ad6def1705d14c002806a70e9db";
  }

  static const char* value(const ::target_detector::MarkerPixelArray_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x44de9ad6def1705dULL;
  static const uint64_t static_value2 = 0x14c002806a70e9dbULL;
};

template<class ContainerAllocator>
struct DataType< ::target_detector::MarkerPixelArray_<ContainerAllocator> >
{
  static const char* value()
  {
    return "target_detector/MarkerPixelArray";
  }

  static const char* value(const ::target_detector::MarkerPixelArray_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::target_detector::MarkerPixelArray_<ContainerAllocator> >
{
  static const char* value()
  {
    return "std_msgs/Header header\n"
"MarkerPixel[] markers\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: target_detector/MarkerPixel\n"
"# AR 码像素坐标\n"
"uint32 id          # 标签 ID\n"
"float32 u          # 像素列坐标 (x)\n"
"float32 v          # 像素行坐标 (y)\n"
;
  }

  static const char* value(const ::target_detector::MarkerPixelArray_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::target_detector::MarkerPixelArray_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.markers);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct MarkerPixelArray_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::target_detector::MarkerPixelArray_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::target_detector::MarkerPixelArray_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "header: ";
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "markers: ";
    if (v.markers.empty() || false)
      s << "[";
    for (size_t i = 0; i < v.markers.size(); ++i)
    {
      if (false && i > 0)
        s << ", ";
      else if (!false)
        s << std::endl << indent << "  -";
      Printer< ::target_detector::MarkerPixel_<ContainerAllocator> >::stream(s, false ? std::string() : indent + "    ", v.markers[i]);
    }
    if (v.markers.empty() || false)
      s << "]";
  }
};

} // namespace message_operations
} // namespace ros

#endif // TARGET_DETECTOR_MESSAGE_MARKERPIXELARRAY_H
